### ISSUE TITLE
Message Not Found user Sign Up

### ISSUE THREAD

**Issue by teten-nugraha** [ridwanfathin/blog-server#14]
![signup1](https://user-images.githubusercontent.com/22310112/46646873-fc2b9080-cbb6-11e8-95c1-f10d41aaa778.png)
![signup2](https://user-images.githubusercontent.com/22310112/46646875-fdf55400-cbb6-11e8-9799-5faac75d82f5.png)

saya mencoba mengakses url sign up tapi response nya terus seperti itu

**Comment by ridwanfathin** [comment]
Tadi jadi sekalian benerin route nya biar sesuai sama :
- https://cloud.google.com/apis/design/
- https://github.com/Microsoft/api-guidelines/blob/master/Guidelines.md

udah di cek lagi lancar, tapi gatau kenapa ga bisa publish api docsnya, ambil disini aja:
https://www.getpostman.com/collections/185a3b465277caffacc8
